export { default as Add } from './Add'
export { default as Home } from './Home'
export { default as Artists } from './Artists'
export { default as Artist } from './Artist'
export { default as NotFound } from './NotFound'
